### PR TITLE
Proper build output

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
Confirmation that build works and allows to render `DatePicker` – https://codesandbox.io/s/condescending-sinoussi-chuvd?file=/package.json

**Review by oliviertassinari — APPROVED** [review]

**Comment by eps1lon** [comment]
>  oliviertassinari requested a review from eps1lon 20 minutes ago

Anything specific I should take a look at here? This looks well done?

**Comment by oliviertassinari** [comment]
@eps1lon Nothing specific, considering it affects the build I thought it could interest you.

**Comment by eps1lon** [comment]
> Nothing specific, considering it affects the build I thought it could interest you.

**Pull request merged**
