### PR TITLE
[DateTimePicker] Migrate tests 

### PR DESCRIPTION
**Pull request by dmtrKovalenko**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by dmtrKovalenko** [comment]
@oliviertassinari can you point me please which of my changes could be a reason of

```
  1) "after each" hook for "calls the appropriate callbacks for each transition":
     TypeError: Cannot read property 'advanceTimersByTime' of null
      at Object.then (node_modules/@testing-library/react/dist/flush-microtasks.js:57:14)
```

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Thanks for the report. What do you think about this fix?

```diff
diff --git a/test/utils/setup.js b/test/utils/setup.js
index 7f8712c1e..1ec442c7d 100644
--- a/test/utils/setup.js
+++ b/test/utils/setup.js
@@ -10,7 +10,9 @@ require('@babel/register')({

 // Enable missing act warnings: https://github.com/facebook/react/blob/v16.13.1/packages/react-reconciler/src/ReactFiberHooks.js#L965
 // TODO: Revisit once https://github.com/facebook/react/issues/15439 is resolved.
-global.jest = null;
+global.jest = {ù
+  // https://github.com/testing-library/react-testing-library/blob/b82773cef7fc69349a55faf3b79eabc1e4ba4eeb/src/flush-microtasks.js#L60
+  advanceTimersByTime: () => {},
+};

 createDOM();
 require('./init');
```

@eps1lon the `useFakeTimers` helper of sinon sets `setTimeout.clock`, [we set](https://github.com/mui-org/material-ui/blob/bf3fb8f5fb3576bb0a336f3bf5a4ae636286935b/test/utils/setupJSDOM.js#L8) global.jest to null (typeof null === object). In this condition, we can enter into [the branch that throw](https://github.com/testing-library/react-testing-library/blob/b82773cef7fc69349a55faf3b79eabc1e4ba4eeb/src/flush-microtasks.js#L60).

**Review by oliviertassinari — CHANGES_REQUESTED** [review]
running `yarn prettier` outputs a lot of changes

**Comment by eps1lon** [comment]
I think what I arrived at is that `getIsUsingFakeTimers` should always return false at this point. Here it seems you didn't restore real timers in between tests.

**Comment by oliviertassinari** [comment]
Interesting, so we should replace https://github.com/mui-org/material-ui/blob/2c97b19c2ea31f1208e508bd089e7102701dbdb3/packages/material-ui/src/Grow/Grow.test.js#L43 with a afterEach?

**Comment by eps1lon** [comment]
> Interesting, so we should replace [https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Grow/Grow.test.js#L43](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Grow/Grow.test.js?rgh-link-date=2020-08-20T07%3A57%3A56Z#L43) with a afterEach?

Definitely. I guess this wasn't caught because it's not using testing-library yet.

**Comment by oliviertassinari** [comment]
Should we backport 3333756ac26a60f5bc29fe45ea452eb6e6423edf into the main repository?

**Review by oliviertassinari — APPROVED** [review]

**Pull request merged**
